const STATUS_CREATED = 201;
const STATUS_BAD_REQUEST = 400;
const STATUS_ERROR_ID = 404;
const STATUS_ERROR_SERVER = 500;
const STATUS_SUCCESS = 200;
const STATUS_UNAUTHORIZED = 401;

export {
  STATUS_CREATED,
  STATUS_ERROR_ID,
  STATUS_ERROR_SERVER,
  STATUS_BAD_REQUEST,
  STATUS_SUCCESS,
  STATUS_UNAUTHORIZED,
};
